create-cff:
  image: python:3.11
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH
  script:
  # Install FACILE-RS
  - pip install FACILE-RS
  - git config --global user.name "${GITLAB_USER_NAME}"
  - git config --global user.email "${GITLAB_USER_EMAIL}"
  # See https://facile-rs.readthedocs.io/en/latest/apidocs/facile_rs/facile_rs.create_cff.html for more information about this command
  - facile-rs cff create
  # Ignore the remaining steps if you don't want to push the generated CFF file to the repository
  # To simply visualize the generated CFF file in the CI job logs, you can use:
  #- cat ${CFF_PATH}
  - git add ${CFF_PATH}
  # Commit only if CFF file has been updated
  - git diff-index --quiet HEAD || git commit -m 'Update CFF file'
  # Push to the repository, but do not trigger CI
  - git push -o ci.skip "https://PUSH_TOKEN:${PRIVATE_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_BRANCH}"