archive-radar:
  stage: archive
  image: python:3.11
  rules:
  - if: $CI_COMMIT_TAG =~ /^v/
  before_script:
  - pip install FACILE-RS
  script:
  - >
    facile-rs radar upload --no-sort-authors
    $RELEASE_ARCHIVE_URL